### ISSUE TITLE
How to make the best of CCDS.txt and custom BED file?

### ISSUE THREAD

**Issue by biocyberman** [robinandeer/chanjo#116]
Hi,
Thank you very much for chanjo. It has become one of my indispensable tools. I have been using it since it only support coordinates from CCDS.txt. It is nice now that I can annotate my own BED file, but I still find CCDS-based annotation useful, especially for the cases where my BED intervals are overlapped. However, I happened to find out that some genes with official HGNC's symbols are missing in CCDS, for example, C1R gene. So I turn to my BED file. The file is from NimbleGene's "SeqCap EZ Human Exome Library v3.0". Below is how it looks for C1R gene. My question is, how do I annotate this BED file and query coverage/completeness for selected genes or and for whole exome?

Thanks
Vang
```BED
SeqCap_EZ_Exome_v3_capture.bed                                                                                                                                                                                        [11:54AM]
chr12   7187784 7187949 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7188054 7188325 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7188352 7188566 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7188572 7188709 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7189276 7189436 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7241100 7241174 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7241191 7241481 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7241490 7241568 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7241894 7241972 gn|C1R;ens|ENSG00000159403;vega|OTTHUMG00000168149
chr12   7242004 7242171 gn|C1R;gn|C1RL;ccds|CCDS8573;ens|ENSG00000139178;ens|ENSG00000159403;vega|OTTHUMG00000168144;vega|OTTHUMG00000168149
chr12   7242304 7242399 gn|C1R;gn|C1RL;ccds|CCDS8573;ens|ENSG00000139178;ens|ENSG00000159403;vega|OTTHUMG00000168144;vega|OTTHUMG00000168149
chr12   7242620 7242806 gn|C1R;gn|C1RL;ccds|CCDS8573;ens|ENSG00000139178;ens|ENSG00000159403;vega|OTTHUMG00000168144;vega|OTTHUMG00000168149
chr12   7244000 7244149 gn|C1R;gn|C1RL;ccds|CCDS8573;ens|ENSG00000139178;ens|ENSG00000159403;vega|OTTHUMG00000168144;vega|OTTHUMG00000168149
chr12   7244214 7244352 gn|C1R;gn|C1RL;ccds|CCDS8573;ens|ENSG00000139178;ens|ENSG00000159403;vega|OTTHUMG00000168144;vega|OTTHUMG00000168149
chr12   7244895 7245074 gn|C1R;gn|C1RL;ccds|CCDS8573;ens|ENSG00000139178;ens|ENSG00000159403;vega|OTTHUMG00000168144;vega|OTTHUMG00000168149
```

**Comment by cboustred** [comment]
Hi Robin,

Related to this issue, is there a way to keep the CCDS regions that are 'Withdrawn' as well as Public?

I see in the current CCDS convertor ('core.py') a filter is applied to keep only 'Public' CCDS genes, the list of genes I have been asked to provide coveage for also includes some which are 'Withdrawn' from CCDS.

I've tried a few hacks of core.py, 

filter(grep('Public'), grep('Withdrawn')),
OR
filter(grep('Public')), 
filter(grep('Withdrawn')),
OR
filter(grep(['Public', 'Withdrawn'])),
OR
filter(grep('Public', 'Withdrawn')),

But, after rebuild none of these  work

Any tips on how I could achieve this would be much appreciated!

Thanks!

Chris

**Comment by biocyberman** [comment]
@cboustred Just a quick note, I haven't tested yet: try  filter(grep('Public|Withdrawn'))

**Comment by cboustred** [comment]
Cheers, will give that I go! As a hack in the end I just used sed to replace all the 'Withdrawn' statements with 'Public' in the .txt before conversion to BED. There were then some further issues with some of the rows missing start / end coordinates but I fudged that too:

sed 's/Withdrawn/Public/g' CCDS.current.txt | awk '$10 != "-" {print $0}' > CCDS.current_all_pub.txt

**Comment by robinandeer** [comment]
I'll close this for now, dropping the convert tool for the upcoming release of 3.0.0 where we will define a more useful python API
