### ISSUE TITLE
Quality scores

### ISSUE THREAD

**Issue by cboustred** [robinandeer/chanjo#123]
Hi Robin,

I have a question regarding quality scores in sequence reads / bam files.

Does Chanjo take phred-like base qualities and / or read mapping qualities into account when calculating coverage over a particular region e.g. if a position is covered 100X but all the bases at this position have a really low phred-like score are they included in the coverage calculation for that base? 

Or should I do some pre-processing of my BAM alignments before using chanjo?

Thanks again, great tool!

Chris

**Comment by robinandeer** [comment]
Hi Chris - thanks for a great comment!

Chanjo delegates reading BAM-files to Samtools pilup. Here, you can see [the actual call][call]. This means that whatever Samtools does in terms of filtering will trickle down to Chanjo but also that Chanjo won't do any filtering beyond this. That said, as far as I can tell Samtools will **use all reads available** for pileup.

There's currently (v2.3.0) no logic or output options in Chanjo that relates to quality scores or filtering low quality reads.

When we use Chanjo internally we always use the most complete BAM alignments, that is after mark duplicates and realignment. I think this is generally a good idea. Chanjo is not trying to be particularly smart about most things.

I will also update the documentation to explain these things more clearly. Thanks again for pointing this important point out.

[call]: https://github.com/robinandeer/chanjo/blob/master/chanjo/depth_reader/core.py#L111

**Comment by robinandeer** [comment]
Just for my own reference:

Samtools mpileup doesn't filter duplicates (https://www.biostars.org/p/12824/)

**Comment by cboustred** [comment]
Thanks Robin,

So to get coverage without duplicate reads using chanjo, duplicate reads
first have to be *removed* (rather than just marked) from the BAM file file
prior to running chanjo.

Another flag I'm not sure mpileup takes into account is 0x100 (secondary
alignments). Its my intention to also filter these out prior to running
Chanjo coverage on my BAMs.

So my input bams will be:

samtools view -q 20 -F 0x400 -F 0x100 raw.bam > clean.bam

or perhaps:

samtools view -q 20 -F 0x400 -F 0x100 [my bam] | chanjo ...

How does that look?

Any other suggestions greatly received

Thanks again,

BW

Chris

**Comment by robinandeer** [comment]
We will discuss this topic tomorrow with some others that might have different perspectives and expertise - hopefully after that I can give you more informed advice :smiley:

**Comment by robinandeer** [comment]
@cboustred: we are finally moving to sambamba for processing BAM-files

They do take this into account (duplicates and low quality reads) so that should make this mess go away :smile:
