### ISSUE TITLE
Support CRAM files

### ISSUE THREAD

**Issue by lbeltrame** [robinandeer/chanjo#129]
pysam supports them in the latest versions, so does samtools, so this is IMO probably doable.

**Comment by robinandeer** [comment]
Do you know if they have already documented the new interface? I can't find it so easily...

**Comment by lbeltrame** [comment]
> Do you know if they have already documented the new interface? I can't find
> it so easily...

The help (sparsely) mentions a reference_filename in the AlignmentFile 
initializer for supplying a reference FASTA file, but I am not sure if it's 
required for reading (but samtools basically needs it, according to my limited 
empirical experience).

**Comment by robinandeer** [comment]
moving to sambamba - I hope they support CRAM files, that would be awesome!

Otherwise, turn to their repo :+1:
