### ISSUE TITLE
Add examples on how to annotate files with the API

### ISSUE THREAD

**Issue by lbeltrame** [robinandeer/chanjo#130]
I'm currently struggling to replicate the behavior of ``annotate`` (including adding sample IDs) using the API. A couple of examples would be helpful.

**Comment by robinandeer** [comment]
Sorry about not having had much time to work on and support Chanjo recently

I would advice you to look into [Sambamba](https://github.com/lomereiter/sambamba) - they provide the same functionality for getting "completeness" with some nice improvements!
