### ISSUE TITLE
arbitrary metrics

### ISSUE THREAD

**Issue by roryk** [robinandeer/chanjo#133]
What do you think about separating out the completeness and coverage columns and instead having it be metric and value. Then you should store arbitrary metrics about a region in the database, not just completeness and coverage?

**Comment by robinandeer** [comment]
That's worth thinking about for sure :smiley: 

Just so we are on the same page: are you thinking this would add another table to the schema? That would then be linked to for example ``interval_data``?

**Comment by roryk** [comment]
I'm a bad person to be thinking about database design but I was thinking instead of say a **coverage** and **completeness** column it would instead be like a plyr melted-style **statistic** and **value**. Then you could jam whatever statistics you wanted to put in there, so like "coverage", 50 "completeness", 0.5  "cv", 1, etc, without having the extra rigamarole of adding an extra column for every new statistic you wanted to precompute and store.

**Comment by robinandeer** [comment]
I understand now! (this is just for my own reference :sweat_smile: )

I will just double the rows in the ``interval_data`` (or whatever I name it) and put on each row the "statistic", "value", "sample", and "parent_id". That seems like a very nice and future proof idea - thanks Rory!

I'll add it to the next major release
