### ISSUE TITLE
chanjo Dockered in NGSeasu

### ISSUE THREAD

**Issue by snewhouse** [robinandeer/chanjo#135]
Hi
First pass and getting it in our environment - not had a deep dive into it yet

[ngseasy-chanjo](https://registry.hub.docker.com/u/compbio/ngseasy-chanjo/)
```
docker pull compbio/ngseasy-chanjo:1.0
```

more soon

Steve

**Comment by robinandeer** [comment]
That's cool!

My local Docker setup is a bit of a mess but I'll look into it again
I'm watching this with interest

**Comment by robinandeer** [comment]
Closing some issues - please keep us updated if you continue to work on the chanjo plugin!

We'd be happy to help with questions on usage or integration
