### ISSUE TITLE
getting coverage data out of the database

### ISSUE THREAD

**Issue by roryk** [robinandeer/chanjo#136]
Once I've loaded coverage data into the database, is there a way to get it out by a certain region? Or should I roll my own SQL queries?

**Comment by robinandeer** [comment]
Yeah, chanjo itself isn't terribly helpful in getting data out of the database once imported. I've intended to build in some basic queries into the CLI but haven't gotten around to it.

If you figure out some interesting SQL queries I would be super happy if you shared them in an issue or blog post or whatever!

**Comment by robinandeer** [comment]
Closing this in favour of already covered in #118
