### ISSUE TITLE
Use indexes to speed up queries

### ISSUE THREAD

**Issue by robinandeer** [robinandeer/chanjo#168]
The report generation is too slow at the moment so I will investigate if adding indexes will help out in speeding some of the more demanding out

**Comment by robinandeer** [comment]
@moonso: if you can suggest how to compose smart indexes that would be awesome! hehe

**Comment by moonso** [comment]
Sure we can think about this together

**Comment by robinandeer** [comment]
I believe I've solved the immediate issue by adding a new index on the `exon_stat.metric` column.

We probably need to optimize further in the future but I believe this is good for now
